services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_ENV: ${APP_ENV}
    env_file:
      - .env
    image: ledger-app
    container_name: ledger-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - "${APP_PORT}:${APP_PORT}"
  worker:
    image: ledger-app
    container_name: ledger-worker
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: ["/bin/sh", "-c", "exec sh scripts/start.worker.sh"]
    depends_on:
      - redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
  db:
    image: postgres:16-alpine
    container_name: ledger-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgsql_data:/var/lib/postgresql/data
  redis:
    image: redis:8-alpine
    container_name: ledger-redis
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  pgsql_data:
  redis_data:
